blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/moshehbenavraham/Napkin-AI-API/discussions
    about: Please ask and answer questions here
  - name: Napkin AI Documentation
    url: https://docs.napkin.ai/
    about: Check the official Napkin AI documentation